// BEGIN
// SET CHOICES
const choices = ["rock", "paper", "scissors"];
// GET COMPUTER CHOICE

// GET USER CHOICE

// IF USER CHOICE IS ROCK AND COMPUTER CHOICE IS SCISSORS
// THEN USER WINS

// ELSE IF USER CHOICE IS SCISSORS AND COMPUTER CHOICE IS ROCK
// THEN COMPUTER WINS

// ELSE IF USER CHOICE IS PAPER AND COMPUTER CHOICE IS ROCK
// THEN USER WINS

// ELSE IF USER CHOICE IS ROCK AND COMPUTER CHOICE IS PAPER
// THEN COMPUTER WINS

// ELSE IF USER CHOICE IS SCISSORS AND COMPUTER IS PAPER
// THEN USER WINS

// ELSE IF USER CHOICE IS PAPER AND COMPUTER IS SCISSORS
// THEN COMPUTER WINS

// ELSE IF USER CHOICE IS EQUAL TO COMPUTER CHOICE
// THEN RESET GAME

// ENDIF